print("welcome to arithmatic world :")
a=int(input("ENter a number"))
b=int(input("ENter a number"))
print("simple Arithmatic opration on A or B number ")
print("Addition is       :",a+b)
print("Substraction is   :",a-b)
print("Multiplication is :",a*b)
print("Division is       :",a/b)
print("thank you for visiting")